### ISSUE TITLE
Page validation failed

### ISSUE THREAD

**Issue by bennycode** [readmeio/rdme#743]
I am using the `readmeio/rdme` action and discovered this week that it sometimes fails with the following output:

> rdme openapi calculate-api-oas-prod.json --key=*** --id=$OPEN_API_SPEC_ID_prod
> - Validating the API definition located at calculate-api-oas-prod.json...
> - Staging your API definition for upload...
> - Updating your API docs in ReadMe...
> ✖ Updating your API docs in ReadMe...
> Error: Unknown error (Page validation failed: project: Path `project` is required., category: Path `category` is required.).

This is how I am using the action:

```
- uses: readmeio/rdme@8.5.0
  with:
    rdme: openapi calculate-api-oas-${{ inputs.STAGE }}.json --key=${{ secrets.README_IO_TOKEN}} --id=$OPEN_API_SPEC_ID_${{ inputs.STAGE }}
```

If I rerun the failed job, then it sometimes succeeds, so the bug seems to be flaky. 

Do you have insights why page validation can fail?

**Comment by kanadgupta** [comment]
Hi @bennycode! We're aware of some validation flakiness issues that have cropped up recently. When was the last time you saw this error?

**Comment by kanadgupta** [comment]
Thanks! A couple more questions:

1. Approximately how often are you seeing this error?
2. Is the error message always `Page validation failed: project: Path project is required., category: Path category is required.` or are you seeing other messages too?

**Comment by bennycode** [comment]
1. We see this error multiple times a day, 5/6 commits fail in their status checks because of that
2. Somestimes we also see this message: `Error: We're sorry, your upload request timed out. Please try again or split your file up into smaller chunks.`

Latest failure was just 2 minutes ago.

**Comment by kanadgupta** [comment]
Got it, thanks! Do you have an approximate failure percentage rate? The reason I ask is because this error seems to be intermittent and we've had trouble reproducing.

**Comment by bennycode** [comment]
The failure rate is around 80%.

**Comment by kanadgupta** [comment]
Yikes 😬 we just shipped a database configuration change within the last couple hours that might have fixed this, can you confirm?

**Comment by kanadgupta** [comment]
Hi @bennycode — we've had customers write in that this flaky issue has been resolved for them. I'm going to close this out but if you're still running into issues feel free to open up another issue.

**Comment by bennycode** [comment]
Great, thank you for the feedback! It looks also resolved now for us. 👍

**Comment by igrek8** [comment]
@kanadgupta we are still getting the exact same error. Can your team please take a look at it?
